config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  # 顧客用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
   root to: "homes#top"
  
  scope module: :public do
    get '/about' => 'homes#about', as: 'about'
    resources :users, only:[:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :teams, only:[:index, :edit, :create, :update, :destroy]
    resources :competitions, only:[:new, :create, :index, :show, :edit, :update, :destroy]
    resources :events, only:[:new, :create, :index, :show] do
      resource :favorites, only:[:create, :destroy]
      resources :event_comments, only:[:create]
    end
    # 検索機能
    get "search" => "searches#search"
    # タグ検索
    get "search_tag"=>"events#search_tag"
    # 通知機能
    resources :notifications, only:[:index]
  end
  

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    root to: 'homes#top'
    resources :genres, only:[:new, :create, :index, :edit, :update]
    resources :events, only:[:index]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :competitions, dependent: :destroy
  has_many :event_comments, dependent: :destroy
  has_many :event_tags, dependent: :destroy
  has_many :tags, through: :event_tags
  has_one_attached :image
  
  has_many :notifications, dependent: :destroy
  
  # いいね
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @event = Event.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @event = Event.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @event = Event.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @event = Event.where("name LIKE?","%#{word}%")
    else
      @event = Event.all
    end
  end
  
  def tags_save(tag_list)
    unless self.tags.empty?
      event_tags_records = EventTag.where(event_id: self.id)
      event_tags_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.find_or_create_by(name: tag)
      self.tags << inspected_tag
    end
  end
  
  # コメント通知
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = EventComment.select(:user_id).where(event_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, event_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    # save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, event_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      event_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :notifications, dependent: :destroy
end

app/models/event_tag.rb
class EventTag < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :competitions, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :event, optional: true
  belongs_to :event_comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :event_tags, dependent: :destroy
  has_many :events, through: :event_tags
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :teams, dependent: :destroy
  has_many :event_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dancers Event</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="d-flex flex-column vh-100">
    <header class="p-3 mb-2 bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">トップ画面</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ",user_path(current_user) %>
            </li>
            <li class="nav-item">
              <%= link_to "イベント作成", new_competition_path %>
            </li>
            <li class="nav-item">
              <%= link_to "イベント一覧", events_path %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト",destroy_user_session_path, method: :delete %>
            </li>
            <li>
              <%= form_with url: search_path, local: true, method: :get do |f| %>
                <%= f.text_field :word %>
                <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                <%= f.submit "検索" %>
              <% end %>
            </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "イベント一覧", admin_events_path %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト",destroy_admin_session_path, method: :delete %>
              </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録",new_user_registration_path %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン",new_user_session_path %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>誰でもダンスイベントの投稿、閲覧を</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>